### ISSUE TITLE
Add Retry Logic for 500-Level HTTP Errors

### ISSUE THREAD

**Issue by zbuchheit** [PaloAltoNetworks/scm-go#1]
### Is your feature request related to a problem?

Currently there isn't any retry logic to retry 500 level errors. There is retry logic for [429 responses](https://github.com/PaloAltoNetworks/scm-go/blob/f12af147098c5d9d7dbece3baa654329e4af686c/client.go#L468-L472). As per the [documentation](https://pan.dev/prisma-cloud/api/cspm/api-errors/#reattempting-requests-that-fail-due-to-a-server-error) it is recommended to retry a 5xx error. Please add the ability to retry 5xx level errors.

### Describe the solution you'd like

Add retry logic to handle 5xx errors as transient.

### Additional context

Encountering an issue when attempting to use the TF provider I occasionally will get a 502 transient error when attempting to operate on large amounts of resources.

**Comment by shinmog** [comment]
This fix contained in the v0.9.2 `terraform-provider-scm` release
